name:                fileSizeBrowser
version:             0.1.0.0
github:              "githubuser/fileSizeBrowser"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fileSizeBrowser#readme>

dependencies:
- base >= 4.7 && < 5
- unix-compat == 0.5.*
- directory == 1.3.*
- filepath == 1.4.*
- ansi-terminal == 0.11

library:
  source-dirs: src

executables:
  fileSizeBrowser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fileSizeBrowser

tests:
  fileSizeBrowser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fileSizeBrowser
